name: Build APK + Auto Version

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set branch name
        id: vars
        run: echo "BRANCH=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute
        run: chmod +x gradlew

      # --- автоинкремент версии ---
      - name: Bump version
        run: |
          FILE=version.properties

          if [ ! -f $FILE ]; then
            echo "VERSION_CODE=1" > $FILE
            echo "VERSION_NAME=1.0.0" >> $FILE
          else
            CODE=$(grep VERSION_CODE $FILE | cut -d'=' -f2)
            NAME=$(grep VERSION_NAME $FILE | cut -d'=' -f2)

            CODE=$((CODE+1))

            echo "VERSION_CODE=$CODE" > $FILE
            echo "VERSION_NAME=$NAME" >> $FILE
          fi

      - name: Commit version
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: version.properties
          commit_message: "ci: bump version"
          branch: ${{ env.BRANCH }}

      # --- сборка ---
      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: app/build/outputs/apk/debug/*.apk
